package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

// FillClassToCapacity inserts as many seed-student bookings as needed to
// take the named class to capacity. Used by the join-waitlist integration
// test so the under-test student lands on a guaranteed-full class without
// the test itself having to drive 16 separate sign-in flows.
//
// Skips users who already have a booking against the class, and only
// picks users who hold an eligible entitlement (matching class type +
// remaining credits if credit-kind). Returns the number of bookings
// minted on this call (0 means the class was already full).
func (s *Store) FillClassToCapacity(ctx context.Context, studioID, classID string) (int, error) {
	var (
		capacity, classTypeID string
		cap, booked           int
	)
	err := s.db.QueryRowContext(ctx, `
		SELECT c.capacity, c.class_type_id,
		       (SELECT COUNT(*) FROM bookings b
		         WHERE b.class_id = c.id AND b.status = 'booked')
		  FROM classes c
		 WHERE c.id = ? AND c.studio_id = ?`,
		classID, studioID,
	).Scan(&cap, &classTypeID, &booked)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, ErrNotFound
	}
	if err != nil {
		return 0, err
	}
	_ = capacity
	needed := cap - booked
	if needed <= 0 {
		return 0, nil
	}

	// Community students with ANY entitlement (active or not) excluding
	// anyone already booked on this class. We deliberately don't filter
	// on entitlement class-type / credits here — these are filler rows
	// for waitlist tests, not real bookings. The schema's FK on
	// entitlement_id is the only thing we need to satisfy. ORDER BY id
	// keeps the picks deterministic across re-seeds.
	_ = classTypeID
	rows, err := s.db.QueryContext(ctx, `
		SELECT u.id, e.id
		  FROM users u
		  JOIN entitlements e ON e.user_id = u.id
		 WHERE u.studio_id = ?
		   AND u.role      = 'student'
		   AND NOT EXISTS (
		     SELECT 1 FROM bookings b
		      WHERE b.class_id = ?
		        AND b.user_id  = u.id
		   )
		 GROUP BY u.id
		 ORDER BY u.id ASC LIMIT ?`,
		studioID, classID, needed,
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	type pick struct{ userID, entID string }
	var picks []pick
	for rows.Next() {
		var p pick
		if err := rows.Scan(&p.userID, &p.entID); err != nil {
			return 0, err
		}
		picks = append(picks, p)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	inserted := 0
	for _, p := range picks {
		// INSERT OR IGNORE handles the UNIQUE(class_id, user_id, is_plus_one)
		// case where the user already has a cancelled booking on this class
		// — the row count reflects only newly-minted bookings.
		res, err := s.db.ExecContext(ctx, `
			INSERT OR IGNORE INTO bookings
			    (id, studio_id, class_id, user_id, entitlement_id, is_plus_one,
			     booked_by_role, cancel_cutoff_hours, status, checkin_token)
			    VALUES (?, ?, ?, ?, ?, 0, 'student', 12, 'booked', ?)`,
			NewID(), studioID, classID, p.userID, p.entID, NewID(),
		)
		if err != nil {
			return inserted, fmt.Errorf("insert filler booking: %w", err)
		}
		if n, _ := res.RowsAffected(); n > 0 {
			inserted++
		}
	}

	return inserted, nil
}

// ResetTestState rolls back any non-seed state added during a test session so
// the next test run starts from a clean, fully-seeded baseline. Used by the
// dev-only POST /dev/reset-test-state endpoint that integration tests hit at
// the top of each scenario.
//
// "Seed-owned" rows use deterministic IDs (`sd_…`, `bk_…`, `ent_…`,
// `cls_wk0_…`, `cls_wk1_…`, `cls_crs_…`, `cls_workshop_…`, plus the constants
// declared at the top of seed.go). Anything else was minted by app traffic
// during a test — that's what we delete.
//
// Order matters because of FK constraints: child rows first.
func (s *Store) ResetTestState(ctx context.Context) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	// `seed%` covers `sd_…` slugs, plus the `bk_maya_*` and `ent_maya`
	// constants. Anything with a NanoID gets cleaned up.
	stmts := []string{
		// Restore the seed bookings that earlier tests may have cancelled or
		// marked. `bk_maya_upcoming` is the obvious one — the cancel test
		// flips it to status='cancelled'; the check-in test needs it active.
		`UPDATE bookings
		    SET status = 'booked', outcome = NULL, cancelled_at = NULL,
		        attendance_marked_by = NULL
		  WHERE id LIKE 'bk_%' AND status != 'booked'`,
		// Re-mint a fresh check-in token for any seed booking that lost one
		// after a scan.
		`UPDATE bookings
		    SET checkin_token = lower(hex(randomblob(8)))
		  WHERE id LIKE 'bk_%' AND checkin_token IS NULL`,

		// Notifications generated by booking flow (booking_confirmed etc.).
		// Seed notifications are written with notification IDs starting with
		// `sd_` or `noti_seed_…` — anything else is from a test booking.
		`DELETE FROM notifications
		   WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'bk_%' AND id NOT LIKE 'noti_seed_%'`,

		// Waitlist entries created during tests. We persist history
		// (status='promoted'/'left') for seeded rows but blow away any
		// random-ID rows minted by JoinWaitlist during a test run.
		`DELETE FROM waitlist_entries WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'wl_seed_%'`,

		// Bookings created during tests (parent_booking_id link cascades
		// implicitly here because both rows match the NOT LIKE filter).
		`DELETE FROM bookings
		   WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'bk_%'`,

		// Purchases + entitlements minted during tests. Order: purchases
		// reference entitlements via resulting_entitlement_id but with no FK,
		// and entitlements have no parents — either order is fine.
		`DELETE FROM purchases
		   WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'pur_seed_%'`,
		`DELETE FROM entitlement_class_types
		   WHERE entitlement_id NOT LIKE 'sd_%' AND entitlement_id NOT LIKE 'ent_%'`,
		`DELETE FROM entitlements
		   WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'ent_%'`,

		// Audit + scan rows are append-only; trim non-seed rows so a long
		// dev session doesn't bloat them.
		`DELETE FROM audit_log WHERE id NOT LIKE 'sd_%' AND id NOT LIKE 'audit_seed_%'`,
	}
	for _, q := range stmts {
		if _, err := tx.ExecContext(ctx, q); err != nil {
			return fmt.Errorf("reset (%s): %w", q, err)
		}
	}
	return tx.Commit()
}
