// Minimal Firebase options for the auth emulator.
//
// In production these would be generated by `flutterfire configure` and
// would contain real apiKey / appId values from the Firebase project. For
// emulator-only development the SDK never validates these values once
// useAuthEmulator() is called, so placeholders are fine.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static const String projectId = 'yoga-school-dev';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _web;
    return _web; // mobile/desktop platforms use the same placeholder for now
  }

  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'fake-api-key',
    appId: '1:0000000000:web:0000000000000000',
    messagingSenderId: '0000000000',
    projectId: projectId,
    authDomain: '$projectId.firebaseapp.com',
  );
}
