// Custom Flutter web bootstrap.
//
// Why this file exists:
//   The default bootstrap (generated by `flutter build web`) registers a
//   service worker which aggressively caches the compiled bundle. In dev,
//   that means every code change requires DevTools → Application → Clear
//   storage + Empty cache and hard reload before the new build is visible.
//
//   The fix is two-pronged:
//     1. Tear down any service worker + cache storage left over from a
//        previous session BEFORE loading the new bundle. This guarantees
//        the first request after the page boots is hitting the network,
//        not a stale cached response.
//     2. Skip the SW registration step entirely. With no SW running, the
//        browser's normal HTTP cache rules apply — which the dev server
//        already serves with no-store headers — so every reload sees the
//        latest build.
//
// When this app ships to prod with a CDN that does proper versioned-filename
// caching, restore the SW registration so the PWA install / offline story
// keeps working. The "Before shipping" checklist in README.md tracks this.

{{flutter_js}}
{{flutter_build_config}}

(async () => {
  // 1. Evict everything cached by previous service-worker generations.
  //    `serviceWorker` may be undefined in some browsers/contexts, so guard.
  if ('serviceWorker' in navigator) {
    try {
      const regs = await navigator.serviceWorker.getRegistrations();
      await Promise.all(regs.map((r) => r.unregister()));
    } catch (_) {}
  }
  if ('caches' in window) {
    try {
      const keys = await caches.keys();
      await Promise.all(keys.map((k) => caches.delete(k)));
    } catch (_) {}
  }

  // 2. Load Flutter without registering a service worker. Omitting
  //    `serviceWorkerSettings` is what disables it — passing an empty
  //    object would still register.
  _flutter.loader.load();
})();
